version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.23.2
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - go mod tidy
  build:
    commands:
      - echo Build started on `date`
      - GOOS=linux GOARCH=amd64 go build -o main fetchNutrientHandler.go
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - main
  discard-paths: yes