version: 0.2

phases:
  install:
    runtime-versions:
      go: 1.23.2
    commands:
      - echo "Setting up Go environment..."
      - go version
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - go mod tidy
  build:
    commands:
      - echo "Building processFoodHandler..."
      - go build -o build/processFoodHandler src/processFoodHandler.go

artifacts:
  files:
    - build/processFoodHandler
  discard-paths: yes

cache:
  paths:
    - /go/pkg/mod
    - ~/.cache/go-build
